#line 2 "src/C_lexer.yy.cpp"

#line 4 "src/C_lexer.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[289] =
    {   0,
        0,    0,   98,   96,   95,   94,   82,   96,   96,   88,
       81,   96,   76,   77,   86,   85,   73,   84,   80,   87,
       38,   39,   74,   70,   89,   75,   90,   93,   36,   78,
       79,   91,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   71,   92,   72,
       83,   69,    0,   47,    0,    1,   55,   72,   64,   56,
        0,    0,   53,   61,   51,   62,   52,   63,    0,   42,
        0,    3,   54,   43,   38,    0,    0,   38,   38,    0,
       38,   39,   39,   39,   39,   79,   71,   78,   60,   66,
       68,   67,   59,    0,   36,   57,   36,   36,   36,   36,

       36,   36,   11,   36,   36,   36,   36,   36,   36,   19,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   58,   65,   40,   48,    0,   42,    0,    0,    3,
       42,    0,   43,    0,   41,   38,   38,   38,   38,    0,
       37,   39,   39,   39,   39,   50,   49,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   17,   36,
       20,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,    0,   42,    2,    0,
       42,    0,   43,   41,   38,    0,    0,   37,    0,   37,
       37,   39,    4,   36,    6,    7,   36,   36,   36,   36,

       13,   14,   36,   36,   18,   21,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   33,   36,   36,
        0,   42,    0,    0,    0,   37,   37,    0,   44,   37,
       37,    5,    8,   36,   36,   36,   36,   16,   36,   36,
       24,   36,   36,   36,   36,   36,   36,   31,   36,   36,
       35,    0,   45,    0,    0,   46,   44,   37,   36,   36,
       12,   15,   36,   23,   25,   26,   27,   28,   29,   36,
       36,   36,   45,    0,   45,   46,   36,   10,   36,   30,
       36,   36,   45,    9,   22,   32,   34,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   31,   30,   30,   30,   32,
       30,   30,   30,   30,   33,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   30,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   30,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,    7,    6,    6,    1,    1,    1,    1,    5,    5,
        5,    5,    5,    5,    6,    6,    6,    6,    6,    6,
        6,    6,    7,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[298] =
    {   0,
        0,    0,  648,  649,  649,  649,  623,  641,  642,   43,
       61,  608,  649,  649,  619,   57,  649,   58,   56,   67,
       76,  121,  617,  649,   79,  617,   53,  649,  631,  649,
      649,  615,   71,   62,   78,   79,   96,   80,   90,   99,
       92,   84,  112,  102,   97,  103,   88,  649,   74,  649,
      649,  649,  633,  649,  634,  649,  649,  649,  649,  649,
      117,  627,  649,  649,  649,  649,  649,  649,  618,  154,
      613,    0,  649,  161,   86,  168,  147,  144,  120,  602,
      158,    0,  162,  145,  167,  649,  649,  649,  589,  649,
      649,  649,  583,  570,  583,  649,  105,  114,  190,  193,

      197,  199,  200,  203,  204,  208,  211,   81,  209,  580,
      212,  205,  214,  217,  221,  213,  224,  219,  226,  227,
      228,  649,  649,  649,  649,  231,  649,  576,  101,    0,
      259,  276,  649,  220,  280,  196,  649,  556,  537,    0,
      281,  198,  649,  553,  534,  649,  649,  232,  253,  273,
      251,  271,  276,  277,  292,  295,  297,  284,  573,  298,
      572,  301,  309,  310,  311,  312,  316,  313,  319,  322,
      323,  327,  324,  328,  333,  332,  329,  333,  568,  370,
      649,  355,  373,  649,  649,  307,  348,  353,  393,  312,
      366,  649,  570,  346,  569,  568,  349,  348,  359,  378,

      567,  566,  387,  388,  565,  562,  345,  389,  394,  405,
      400,  398,  410,  412,  415,  409,  411,  560,  416,  419,
      411,  445,  419,  394,  460,  402,  649,  448,  464,  537,
      516,  555,  554,  437,  449,  427,  440,  547,  431,  445,
      542,  460,  433,  462,  472,  446,  476,  541,  481,  452,
      539,  486,  491,  511,  496,  518,  649,  649,  477,  488,
      534,  533,  498,  518,  516,  512,  492,  424,  335,  508,
      503,  509,  649,  535,  541,  649,  514,  245,  491,  238,
      524,  530,  649,  233,  225,  218,  216,  649,  590,  597,
      604,  609,  616,  623,  627,  110,  628

    } ;

static yyconst flex_int16_t yy_def[298] =
    {   0,
      288,    1,  288,  288,  288,  288,  288,  289,  290,  288,
      288,  291,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  292,  288,
      288,  288,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  288,  288,  288,
      288,  288,  289,  288,  290,  288,  288,  288,  288,  288,
      291,  291,  288,  288,  288,  288,  288,  288,  288,  288,
      293,  294,  288,  288,   21,  288,  288,  288,  288,  295,
      288,   22,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  291,  292,  288,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  288,  288,  288,  288,  288,  288,  293,  293,  294,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  296,
      295,  288,  288,  288,  288,  288,  288,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  288,  288,  293,  288,
      288,  288,  288,  288,  288,  296,  297,  288,  288,  288,
      288,  288,  292,  292,  292,  292,  292,  292,  292,  292,

      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      288,  288,  288,  297,  288,  288,  288,  288,  288,  288,
      288,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  288,  288,  288,  288,  288,  288,  288,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  292,  292,
      292,  292,  288,  288,  288,  288,  292,  292,  292,  292,
      292,  292,  288,  292,  292,  292,  292,    0,  288,  288,
      288,  288,  288,  288,  288,  288,  288

    } ;

static yyconst flex_uint16_t yy_nxt[716] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   29,   29,
       29,   29,   29,   29,   30,    4,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   29,   40,   29,   41,   29,
       29,   29,   29,   42,   43,   44,   45,   46,   47,   29,
       29,   29,   48,   49,   50,   51,   57,   58,   59,   64,
       94,   69,   66,   70,   70,   70,   92,   93,   71,   94,
       65,   67,   68,   72,   60,   87,   94,   94,   94,  288,
       73,   74,   94,   75,   75,   76,   94,  122,   94,   88,

       94,   89,   90,   77,   94,   94,   78,   94,   79,   80,
       94,   94,  129,  288,  186,   98,   99,  179,   77,  288,
       94,  102,  288,  100,   81,  124,  113,   97,  107,  101,
      103,  108,   79,  121,  159,   80,   74,  123,   82,   82,
       82,  109,  110,  112,  104,  288,  105,  119,   77,  111,
      138,   83,   62,   84,  120,  106,  149,  114,  115,  134,
      148,  134,  118,   77,  135,  135,  135,  116,  139,   85,
      117,   70,   70,   70,  136,  144,  137,   84,  131,  131,
      131,  126,  127,   74,  127,   76,   76,   76,  132,  133,
      137,  133,  142,  145,  143,   77,  126,  127,  288,  143,

      137,  288,  127,  132,  133,  288,  136,  288,  288,  133,
       77,  288,  288,  288,  137,  142,  288,  288,  143,  288,
      288,  288,  288,  143,  288,  288,  288,  288,  137,  288,
      143,  151,  288,  288,  288,  288,  288,  135,  135,  135,
      288,  288,  153,  177,  150,  177,  288,  152,  178,  178,
      178,  168,  137,  288,  143,  162,  154,  155,  163,  288,
      156,  288,  158,  157,  160,  166,  169,  161,  165,  164,
      170,  171,  172,  174,  176,  175,  131,  131,  131,  288,
      173,  288,  167,  193,  288,  288,  180,  181,  182,  181,
      182,  194,  288,  183,  183,  183,  187,  135,  135,  135,

      288,  180,  181,  288,  196,  288,  288,  181,  184,  288,
      184,  188,  189,  190,  199,  195,  200,  288,  288,  288,
      288,  288,  204,  184,  288,  197,  198,  288,  184,  191,
      288,  288,  288,  189,  201,  288,  288,  190,  223,  203,
      288,  288,  230,  288,  202,  206,  178,  178,  178,  205,
      178,  178,  178,  288,  288,  207,  288,  288,  211,  223,
      231,  127,  210,  127,  209,  215,  208,  288,  212,  218,
      217,  219,  183,  183,  183,  213,  127,  214,  216,  225,
      220,  127,  221,  226,  221,  227,  288,  222,  222,  222,
      183,  183,  183,  232,  234,  288,  288,  288,  227,  239,

      225,  133,  288,  133,  233,  228,  288,  228,  288,  227,
      229,  229,  229,  288,  226,  235,  133,  288,  288,  288,
      288,  133,  227,  288,  288,  254,  236,  288,  222,  222,
      222,  252,  288,  252,  227,  288,  253,  253,  253,  288,
      237,  288,  240,  238,  244,  288,  254,  242,  288,  241,
      245,  243,  246,  288,  288,  249,  247,  288,  227,  248,
      288,  251,  222,  222,  222,  229,  229,  229,  288,  261,
      288,  250,  255,  181,  255,  181,  266,  256,  256,  256,
      288,  229,  229,  229,  288,  288,  263,  259,  181,  288,
      262,  269,  257,  181,  257,  264,  288,  260,  272,  288,

      288,  265,  267,  253,  253,  253,  288,  257,  253,  253,
      253,  288,  257,  256,  256,  256,  288,  288,  270,  273,
      288,  273,  288,  274,  288,  274,  288,  268,  275,  275,
      275,  271,  288,  277,  273,  256,  256,  256,  288,  273,
      279,  288,  288,  278,  285,  281,  276,  288,  276,  288,
      288,  280,  275,  275,  275,  288,  284,  282,  275,  275,
      275,  276,  288,  288,  258,  286,  276,  258,  288,  283,
      288,  283,  287,  288,  288,  288,  288,  288,  288,  129,
      288,  288,  192,  192,  283,  185,  185,  129,  288,  283,
       53,  288,   53,   53,   53,   53,   53,   55,   55,   55,

       55,   55,   55,   55,   61,   62,  147,   61,   61,   61,
       61,   95,  146,   95,   95,   95,  128,  140,  128,  128,
      128,  128,  128,  130,  129,  130,  130,  130,  130,  130,
      141,  141,  224,  125,  224,   61,   56,   54,   96,   94,
       91,   86,   63,   62,   56,   54,   52,  288,    3,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288
    } ;

static yyconst flex_int16_t yy_chk[716] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   10,   10,   11,   16,
       34,   19,   18,   19,   19,   19,   27,   27,   20,   33,
       16,   18,   18,   20,   11,   25,   35,   36,   38,  108,
       20,   21,   42,   21,   21,   21,   47,   49,   39,   25,

       41,   25,   25,   21,   37,   45,   21,   40,   21,   21,
       44,   46,  129,   97,  296,   34,   35,  129,   21,   75,
       43,   36,   98,   35,   21,   61,   42,   33,   38,   35,
       36,   38,   21,   47,  108,   21,   22,   49,   22,   22,
       22,   39,   40,   41,   37,   75,   37,   45,   22,   40,
       79,   22,   61,   22,   46,   37,   98,   43,   43,   77,
       97,   77,   44,   22,   77,   77,   77,   43,   79,   22,
       43,   70,   70,   70,   78,   84,   78,   22,   74,   74,
       74,   70,   70,   76,   70,   76,   76,   76,   74,   74,
       81,   74,   83,   84,   83,   76,   70,   70,   99,   85,

       78,  100,   70,   74,   74,  101,   81,  102,  103,   74,
       76,  104,  105,  112,   81,   85,  106,  109,   83,  107,
      111,  116,  113,   85,  287,  114,  286,  118,  136,  115,
      142,  100,  117,  285,  119,  120,  121,  134,  134,  134,
      148,  284,  102,  126,   99,  126,  280,  101,  126,  126,
      126,  116,  136,  278,  142,  112,  103,  104,  113,  151,
      105,  149,  107,  106,  109,  115,  116,  111,  114,  113,
      117,  118,  119,  120,  121,  120,  131,  131,  131,  152,
      119,  150,  115,  148,  153,  154,  131,  131,  132,  131,
      132,  149,  158,  132,  132,  132,  141,  135,  135,  135,

      155,  131,  131,  156,  151,  157,  160,  131,  135,  162,
      135,  141,  141,  141,  153,  150,  154,  163,  164,  165,
      166,  168,  158,  135,  167,  152,  152,  169,  135,  141,
      170,  171,  173,  141,  155,  172,  174,  141,  186,  157,
      176,  175,  190,  269,  156,  162,  177,  177,  177,  160,
      178,  178,  178,  207,  194,  163,  198,  197,  167,  186,
      190,  178,  166,  178,  165,  171,  164,  199,  168,  174,
      173,  175,  182,  182,  182,  169,  178,  170,  172,  187,
      176,  178,  180,  188,  180,  188,  200,  180,  180,  180,
      183,  183,  183,  194,  198,  203,  204,  208,  191,  207,

      187,  183,  209,  183,  197,  189,  212,  189,  211,  188,
      189,  189,  189,  210,  191,  199,  183,  216,  213,  217,
      214,  183,  191,  215,  219,  224,  200,  220,  221,  221,
      221,  223,  268,  223,  226,  236,  223,  223,  223,  239,
      203,  243,  208,  204,  212,  234,  224,  210,  237,  209,
      213,  211,  214,  240,  246,  217,  215,  235,  226,  216,
      250,  220,  222,  222,  222,  228,  228,  228,  242,  236,
      244,  219,  225,  222,  225,  222,  243,  225,  225,  225,
      245,  229,  229,  229,  247,  259,  239,  234,  222,  249,
      237,  246,  229,  222,  229,  240,  260,  235,  250,  279,

      267,  242,  244,  252,  252,  252,  263,  229,  253,  253,
      253,  271,  229,  255,  255,  255,  270,  272,  247,  253,
      266,  253,  277,  254,  265,  254,  264,  245,  254,  254,
      254,  249,  281,  259,  253,  256,  256,  256,  282,  253,
      263,  262,  261,  260,  279,  271,  256,  251,  256,  248,
      241,  270,  274,  274,  274,  238,  277,  272,  275,  275,
      275,  256,  233,  232,  231,  281,  256,  230,  218,  275,
      206,  275,  282,  205,  202,  201,  196,  195,  193,  179,
      161,  159,  145,  144,  275,  139,  138,  128,  110,  275,
      289,   95,  289,  289,  289,  289,  289,  290,  290,  290,

      290,  290,  290,  290,  291,   94,   93,  291,  291,  291,
      291,  292,   89,  292,  292,  292,  293,   80,  293,  293,
      293,  293,  293,  294,   71,  294,  294,  294,  294,  294,
      295,  295,  297,   69,  297,   62,   55,   53,   32,   29,
       26,   23,   15,   12,    9,    8,    7,    3,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[98] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/C_lexer.flex"
#line 5 "src/C_lexer.flex"


/* Bring in our declarations for token types and
   the yylval variable. */

#include "C_parser.tab.hpp"
#include <stdlib.h>		
#include <string>
#include <iostream>
#include "../include/ast/class_forward_declarations.hpp"		


void yyerror (char const *s);
extern FILE *yyin;
extern FILE *yyout;

int token(int T);
int vtoken(int T);
int type();

int LineNo = 1;			//Used for debugging


// This is to work around an irritating bug in Flex
extern "C" int fileno(FILE *stream);
#line 779 "src/C_lexer.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 32 "src/C_lexer.flex"

#line 999 "src/C_lexer.yy.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 289 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 649 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 33 "src/C_lexer.flex"
{  return vtoken(PREPROCESSOR); LineNo++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "src/C_lexer.flex"
{  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "src/C_lexer.flex"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "src/C_lexer.flex"
{  return token(AUTO);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "src/C_lexer.flex"
{  return token(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "src/C_lexer.flex"
{  return token(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "src/C_lexer.flex"
{ if(contxt.typedefs_) {
				 contxt.TypeDef.TypeSpec = "char";
			} 
				return token(CHAR);
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "src/C_lexer.flex"
{  return token(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 53 "src/C_lexer.flex"
{  return token(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "src/C_lexer.flex"
{  return token(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "src/C_lexer.flex"
{  return token(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "double";
			   } 
			    return token(DOUBLE);
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "src/C_lexer.flex"
{  return token(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 67 "src/C_lexer.flex"
{  return token(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "src/C_lexer.flex"
{  return token(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 71 "src/C_lexer.flex"
{ if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "float";
			  } 
			  return token(FLOAT);
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "src/C_lexer.flex"
{  return token(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 79 "src/C_lexer.flex"
{  return token(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "src/C_lexer.flex"
{  return token(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "int";
			   } 
			     return token(INT);
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "src/C_lexer.flex"
{ if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "long";
			  } 
				return token(LONG);
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 95 "src/C_lexer.flex"
{  return token(REGISTER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "src/C_lexer.flex"
{  return token(RETURN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "short";
			   } 
			    return token(SHORT);
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "signed";
			   } 
				return token(SIGNED);
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 111 "src/C_lexer.flex"
{  return token(SIZEOF); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "src/C_lexer.flex"
{  return token(STATIC); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "src/C_lexer.flex"
{  return token(STRUCT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 117 "src/C_lexer.flex"
{  return token(SWITCH); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "src/C_lexer.flex"
{ contxt.typedefs_ = true;
			  return token(TYPEDEF);
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 123 "src/C_lexer.flex"
{  return token(UNION); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 125 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "unsigned";
			   }
			   return token(UNSIGNED);
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 131 "src/C_lexer.flex"
{  if(contxt.typedefs_) { 
				contxt.TypeDef.TypeSpec = "void";
			} 
			  return token(VOID);
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "src/C_lexer.flex"
{  return token(VOLATILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "src/C_lexer.flex"
{  return token(WHILE); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "src/C_lexer.flex"
{
									
									if(contxt.typedefs_) {
										
										int i=0;
										contxt.TypeDef.DummyName = "";
										contxt.TypeDef.Scope = contxt.newScope;
										while( yytext[i] != NULL){
											contxt.TypeDef.DummyName += yytext[i];
											i++;
										}
										if(contxt.TypeDef.TypeSpec != "int" || "short" || "long" || "char" || "void" || "unsigned" || "signed" || "double" ){

											for(int i(0); i < contxt.TypeAssoc.size(); i++){
											
												if(contxt.TypeAssoc[i].DummyName == contxt.TypeDef.DummyName){
													
													contxt.TypeDef.TypeSpec = contxt.TypeAssoc[i].TypeSpec;
												}
											}
										}
										
										if(contxt.TypeDef.TypeSpec.size() && contxt.TypeAssoc.size() && contxt.TypeAssoc[contxt.TypeAssoc.size()-1].DummyName != contxt.TypeDef.DummyName){
											contxt.TypeAssoc.push_back(contxt.TypeDef);
											contxt.typedefs_ = false;
											
											contxt.TypeDef.TypeSpec = ""; 
											
										}
										else if( contxt.TypeDef.TypeSpec.size() && !contxt.TypeAssoc.size()){
												
											contxt.TypeAssoc.push_back(contxt.TypeDef);
											contxt.typedefs_ = false;
											
											contxt.TypeDef.TypeSpec = ""; 
										}
										
										
										return type();
									}
										
										return type();
									}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 185 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 187 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 189 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 191 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 193 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 195 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 197 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 199 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 201 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 203 "src/C_lexer.flex"
{  return token(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 205 "src/C_lexer.flex"
{  return vtoken(STRING_LITERAL); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 207 "src/C_lexer.flex"
{  return token(ELLIPSIS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 209 "src/C_lexer.flex"
{  return token(RIGHT_ASSIGN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 211 "src/C_lexer.flex"
{  return token(LEFT_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 213 "src/C_lexer.flex"
{  return token(ADD_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 215 "src/C_lexer.flex"
{  return token(SUB_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 217 "src/C_lexer.flex"
{  return token(MUL_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 219 "src/C_lexer.flex"
{  return token(DIV_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 221 "src/C_lexer.flex"
{  return token(MOD_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 223 "src/C_lexer.flex"
{  return token(AND_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 225 "src/C_lexer.flex"
{  return token(XOR_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 227 "src/C_lexer.flex"
{  return token(OR_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 229 "src/C_lexer.flex"
{  return token(RIGHT_OP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 231 "src/C_lexer.flex"
{  return token(LEFT_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 233 "src/C_lexer.flex"
{  return token(INC_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 235 "src/C_lexer.flex"
{  return token(DEC_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 237 "src/C_lexer.flex"
{  return token(PTR_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 239 "src/C_lexer.flex"
{  return token(AND_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 241 "src/C_lexer.flex"
{  return token(OR_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 243 "src/C_lexer.flex"
{  return token(LE_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 245 "src/C_lexer.flex"
{  return token(GE_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 247 "src/C_lexer.flex"
{  return token(EQ_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 249 "src/C_lexer.flex"
{  return token(NE_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 251 "src/C_lexer.flex"
{  return(SEMICOLON); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 253 "src/C_lexer.flex"
{  contxt.newScope++; return('{'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 255 "src/C_lexer.flex"
{  contxt.newScope--;return('}'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 257 "src/C_lexer.flex"
{  return(','); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 259 "src/C_lexer.flex"
{  return(':'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 261 "src/C_lexer.flex"
{  return('='); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 263 "src/C_lexer.flex"
{  return('('); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 265 "src/C_lexer.flex"
{  return(')'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 267 "src/C_lexer.flex"
{  return('['); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 269 "src/C_lexer.flex"
{  return(']'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 271 "src/C_lexer.flex"
{  return('.'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 273 "src/C_lexer.flex"
{  return('&'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 275 "src/C_lexer.flex"
{  return('!'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 277 "src/C_lexer.flex"
{ return(TILDE); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 279 "src/C_lexer.flex"
{  return token(MINUS); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 281 "src/C_lexer.flex"
{  return token(PLUS);  }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 283 "src/C_lexer.flex"
{  return token(MULTIPLY); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 285 "src/C_lexer.flex"
{  return token(DIVIDE); } 
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 287 "src/C_lexer.flex"
{  return token(MODULO); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 289 "src/C_lexer.flex"
{  return token(LT);    }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 291 "src/C_lexer.flex"
{  return token(GT);    }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 293 "src/C_lexer.flex"
{  return('^'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 295 "src/C_lexer.flex"
{  return('|'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 297 "src/C_lexer.flex"
{  return('?'); }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 299 "src/C_lexer.flex"
{ LineNo++; }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 301 "src/C_lexer.flex"
{ /*ignore*/ }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 303 "src/C_lexer.flex"
{ yyerror (yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 305 "src/C_lexer.flex"
ECHO;
	YY_BREAK
#line 1634 "src/C_lexer.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 289 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 289 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 288);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 305 "src/C_lexer.flex"



/* Error handler. This will get called if none of the rules match. */
void yyerror (char const *s)
{
  	fprintf (stderr, "Error: %s\n", s); /* s is the text that wasn't matched */
	std::cerr << "Terminated At line: " << LineNo << " due to Syntax/Lexical error" << std::endl;
	
  	exit(1);
}

int type(){
	int i=0;
	std::string temp;
	while( yytext[i] != NULL){
		temp += yytext[i];
		i++;
	}
	
	for(int i(0); i < contxt.TypeAssoc.size(); i++){
		
		if( temp == contxt.TypeAssoc[i].DummyName && contxt.newScope == contxt.TypeAssoc[i].Scope){
			
			
			if(contxt.TypeAssoc[i].TypeSpec == "int" ){
				temp = "";
				return INT;}
			if(contxt.TypeAssoc[i].TypeSpec == "char"){
				temp = "";
				yylval.text = new std::string("char");
				return CHAR;}
			if(contxt.TypeAssoc[i].TypeSpec == "float"){
				temp = "";
				yylval.text = new std::string("float");
				return FLOAT;}
			if(contxt.TypeAssoc[i].TypeSpec == "double"){
				temp = "";
				yylval.text = new std::string("double");
				return DOUBLE;}
			if(contxt.TypeAssoc[i].TypeSpec == "short"){
				temp = "";
				yylval.text = new std::string("short");
				return SHORT;}
			if(contxt.TypeAssoc[i].TypeSpec == "long"){
				temp = "";
				yylval.text = new std::string("long");
				return LONG;}
			if(contxt.TypeAssoc[i].TypeSpec == "unsigned"){
				temp = "";
				yylval.text = new std::string("unsigned");
				return UNSIGNED;}
			if(contxt.TypeAssoc[i].TypeSpec == "signed"){
				temp = "";
				yylval.text = new std::string("signed");
				return SIGNED;}
			if(contxt.TypeAssoc[i].TypeSpec == "void"){
				temp = "";
				yylval.text = new std::string("void");
				return VOID;}					
		}				
	}
	yylval.text = new std::string(yytext);
	temp = "";
	return IDENTIFIER;
}
	

int token(int T) {
		yylval.text = new std::string(yytext);		
		
		return T;
}

int vtoken(int T){
	if( T == STRING_LITERAL) {	
		std::string temp = yytext;
		std::string temp2;
    		temp[temp.find_first_of('"')] = 0;
    		temp[temp.find_last_of('"')] = 0;
		for ( unsigned i = 0; i < temp.size(); ++i){
			if(temp[i] != 0) {
				temp2 += temp[i];
			}
		}
		yylval.text = new std::string(temp2);
	}

	else{
	        std::string temp = yytext;
		std::string temp2;
    		temp[temp.find_first_of('#')] = 0;
		for ( unsigned i = 0; i < temp.size(); ++i){
			if(temp[i] != 0) {
				temp2 += temp[i];
			}
		}
		yylval.text = new std::string(temp2);
	}	
	
	return T;
}	

/*	int token(int T) {
		
		if( T == IDENTIFIER || T == STRING_LITERAL || T == CONSTANT) {
			return vtoken(T);

		}

		else{
			yylval.text = new std::string(yytext);
			return T;
		}
	}

	int vtoken(int T){
		
		if( T == IDENTIFIER ) {

	        	yylval.text = new std::string(yytext);
		}

		else if( T == CONSTANT ) {

	        	yylval.text = new std::string(yytext);

		}		

		else if( T == STRING_LITERAL) {

			std::string temp = yytext;
			std::string temp2;
		    	temp[temp.find_first_of('"')] = 0;
		    	temp[temp.find_last_of('"')] = 0;
			for ( unsigned i = 0; i < temp.size(); ++i){
				if(temp[i] != 0) {
					temp2 += temp[i];
				}
			}
			yylval.text = new std::string(temp2);
		}
		return T;
	}	
*/

